<?php if (count($this->messages) ) : ?>
<div class="<?php echo $this->flashMessengerClass; ?>">
<?php foreach ($this->messages as $message) : ?>
    <p><?php echo $this->escape($message); ?></p>
<?php endforeach; ?>
</div>
<?php endif; ?>

<div class="result-message">

    <?php if ($this->identity): ?>
        <h2>You are logged in as <?php echo $this->identity ?></h2>

        <a href="/">Back to <?php echo $this->app_name ?></a>
        
        <h4><a href="<?php echo $this->url(array(),'logout'); ?>">Logout</a></h4>
        
    <?php endif; ?>


</div>