<?php if (count($this->messages) ) : ?>
<div class="<?php echo $this->flashMessengerClass; ?>">
<?php foreach ($this->messages as $message) : ?>
    <p><?php echo $this->escape($message); ?></p>
<?php endforeach; ?>
</div>
<?php endif; ?>
<div id="login-options">
    <?php if(isset($this->message)): ?>
    <div id="login-message"><?php echo $this->message ?></div>
    <?php endif; ?>
	<div id="login-internal" class="login-box">
		<h1>Login</h1>
		<?php echo $this->form; ?>
		<div id="login-create-account">
		<div class="or">or</div>
		<a href="<?php echo $this->url(array(),'register'); ?>">Create a new Account</a>
		</div>
		<a id="login-forgot" href="<?php echo $this->url(array(),'forgot-password') ?>">
		Psst! Forgot your login info? Click here for help.
		</a>
	</div>
</div>
